"""Comment, reply voting

Revision ID: a3ca9ba94e90
Revises: 99e9da74cae8
Create Date: 2023-03-25 18:05:20.986357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ca9ba94e90'
down_revision = '99e9da74cae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_content_vote_comment_id_comment'), 'comment', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_content_vote_comment_id_comment'), type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###
